### ISSUE TITLE
Transfer main markdown file out of README.md

### ISSUE THREAD

**Issue by Ivar-Rydstrom** [Weinstein-Classics/Ethan-Frome#4]
I think it would be a good idea to not use the README file as the website information. An actual README file could be nice, and we should eventually transfer the information from the current README file into a different markdown file.

Not  that it really matters, though.

**Comment by Kab1r** [comment]
Now we just need information in the [README File](https://github.com/Weinstein-Classics/Ethan-Frome/blob/master/index.md).
